## baiduPush.yml
name: 'baiduPush'
 
on:
  push:
  schedule:
    - cron: '0 23 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - name: 'Checkout codes' # 步骤一，获取仓库代码
        uses: actions/checkout@v1
      - name: 'Run baiduPush.sh' # 步骤二，执行sh命令文件
        run: npm install && npm run baiduPush # 运行命令。（注意，运行目录是仓库根目录）